# Generated by Django 5.0.3 on 2024-03-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meow',
            options={'ordering': ['-created_at']},
        ),
    ]
